name = "Cobblemon Returns"
author = "Gabriel Afonso"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69f2cf19be9c5e11e0d25070cbac5ea976c52b5849dffe71f0e0866d5f446521"

[versions]
fabric = "0.19.2"
minecraft = "1.21.1"
