name = "Cobblemon Returns"
author = "Gabriel Afonso"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b2a06b5fa1d0a1e3b76aab187bd3c46296bfb0fe26bde60dff128775548a3b8"

[versions]
fabric = "0.19.2"
minecraft = "1.21.1"
