name = "Cobblemon Returns"
author = "Gabriel Afonso"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71f6cf28dbf4899bcc86cba63167e87c02636a38367474f7061a1ed0404b4339"

[versions]
fabric = "0.19.2"
minecraft = "1.21.1"
